// 0x17000284
const GeoLayout money_animation_geo[] = {
   GEO_SWITCH_CASE(18, geo_switch_anim_state),
   GEO_OPEN_NODE(),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_1),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_2),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_3),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_4),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_5),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_6),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_7),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_8),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_9),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_10),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_11),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_12),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_13),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_14),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_15),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_16),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_17),
      GEO_DISPLAY_LIST(LAYER_TRANSPARENT, money_animation_seg4_dl_18),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
